# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a8cd8988d2b0166a29eff90067bf03a6596b6bd4b9a982bc6cf108b8201c6dfb86c442d0941cb6e1f7148cffe8bf3abedeb4a7a7e3cf915b9e0449c1461c31

test:
  secret_key_base: 0139cf57c31b9b4131980dc0623c38345c461d7e512f5a511a939f3fe24ff5187295ac5a044fc5d518aa6bdafb134c63bd53271db3ef4831a1de682163a3c04d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
